### ISSUE TITLE
Add/fix donation alerts

### ISSUE THREAD

**Issue by techguydave** [the-ding-stroders/tds-2020-layouts#12]
Some relevant code is already there. See if you can salvage it, doc. Also:

- [x] Should have dashboard-configurable sound selection/control
- [x] Send simultaneously to Streamaganza Discord channel

**Comment by techguydave** [comment]
Discord notifications added in 9cbd870477ef66c5b64d8f3e1b427918f22eada8.

**Comment by synth3tk** [comment]
Sound selection/control should be implemented in #17.
